### ISSUE TITLE
controller deamonset ports are fixed

### ISSUE THREAD

**Issue by fga1794** [nginxinc/nginx-ingress-helm-operator#143]
we need to deploy nginx ingress. Howerver on openshift, there is a default controller that use default ports 80 & 443.
So we need to custom ports . in the chart helm, the parameters are not variable.

in template Breadcrumbs[nginx-ingress-helm-operator](https://github.com/nginxinc/nginx-ingress-helm-operator/tree/main)/[helm-charts](https://github.com/nginxinc/nginx-ingress-helm-operator/tree/main/helm-charts)/[nginx-ingress](https://github.com/nginxinc/nginx-ingress-helm-operator/tree/main/helm-charts/nginx-ingress)/[templates](https://github.com/nginxinc/nginx-ingress-helm-operator/tree/main/helm-charts/nginx-ingress/templates)
/controller-daemonset.yaml

```
.....
{{ toYaml .Values.controller.lifecycle | indent 10 }}
{{- end }}
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
{{ if .Values.controller.customPorts }}
{{ toYaml .Values.controller.customPorts | indent 8 }}
....
```

can you change it as variable ?

**Comment by vepatel** [comment]
Hi @fga1794 this feature is not available at the moment but is being worked on see https://github.com/nginxinc/kubernetes-ingress/discussions/3724, may I suggest disabling the default controller?

**Comment by lucacome** [comment]
Hi @fga1794 do you need the `hostPort` to be configurable? If so we have an issue here https://github.com/nginxinc/kubernetes-ingress/issues/3613 for that.

**Comment by fga1794** [comment]
Hello @lucacome  i need all this to be configured
`        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443`

**Comment by lucacome** [comment]
@fga1794 can you explain your use case? Do you build a custom NGINX Ingress Controller image and change the ports for the container?

**Comment by fga1794** [comment]
openshift deploy a standard ingress controller that use port 80 & 443. 
So when we tried to deploy nginx ingress controller we got error that the port 80 & 443 are used. So, we think that we need to change this port to used other ones for nginx ingress controller

**Comment by vincentor** [comment]
need the same feature too, when will it be merged?
