### ISSUE TITLE
Unable to create Nginx IngressController with Nginx-Ingress-Operator v1.5.1 and OCP Version v4.13

### ISSUE THREAD

**Issue by a-thorat** [nginxinc/nginx-ingress-helm-operator#159]
**Describe the bug**
Unable to create nging-ingress-controller with Nginx-Ingress-Operator v1.5.1 and OCP Version v4.13

**To Reproduce**
1. Deployed Nginx Ingress Operator v1.5.1 provided by NGINX Inc
2. Tried to create Nginx Ingress Controller through OpenShift Console
3. seeing below error,
       failed to install release: values don't meet the specifications of the
       schema(s) in the following chart(s):
       nginx-ingress:
       open ./v1.26.1/_definitions.json: no such file or directory
       reason: InstallError
Also in events observed 
Chart value "controller.wildcardTLS.cert" overridden to "" by operator's watches.yaml
Chart value "controller.defaultTLS.key" overridden to "" by operator's watches.yaml

**Expected behavior**
A nginx ingress controller instance should get up and running for nginx-ingress-operator

**Environment**
* Version of the NGINX Ingress Operator - release version or a specific commit - Nginx-Ingress-Operator v1.5.1 
* Version of the Ingress Controller - release version or a specific commit - based on above Operator Version
* Version of Kubernetes - Kubernetes Version: v1.26.3+b404935
* Kubernetes platform - OCP v4.13
* Using NGINX or NGINX Plus - NGINX

**Additional context**
If i try to install helm based nginx ingress controller able to get deployed on OCP v4.13

**Comment by vepatel** [comment]
https://github.com/nginxinc/nginx-ingress-helm-operator/pull/161#issuecomment-1697157209

**Comment by vepatel** [comment]
@a-thorat fixed in v1.5.2

**Comment by a-thorat** [comment]
@vepatel  noted with big thank you. let me validate and will keep you posted.
