### ISSUE TITLE
Operator 1.5.1 failed install: open ./v1.26.1/_definitions.json: no such file or directory

### ISSUE THREAD

**Issue by davisli** [nginxinc/nginx-ingress-helm-operator#163]
Installing this version of the operator with supplied YAML file with minimum changes produced the error:

"failed to install release: values don't meet the specifications of the schema(s) in the following chart(s):\nnginx-ingress:\nopen ./v1.26.1/_definitions.json: no such file or directory",

**Describe the bug**

**To Reproduce**
1. Used Openshift Operator Hub to create nginx ingress controller instance

**Expected behavior**

**Your environment**
* Version of the NGINX Ingress Operator - 1.5.1
* Version of the Ingress Controller - default 
* Version of Kubernetes - 1.25.10
* Kubernetes platform (e.g. Mini-kube or GCP) - OCP 4.12.22
* Using NGINX or NGINX Plus - NGINX

**Additional context**
[error_logs_1Sep23.txt](https://github.com/nginxinc/nginx-ingress-helm-operator/files/12496530/error_logs_1Sep23.txt)
[charts_v1alpha1_nginxingress.txt](https://github.com/nginxinc/nginx-ingress-helm-operator/files/12496498/charts_v1alpha1_nginxingress.txt)

**Comment by davisli** [comment]
Just tested with Operator 1.5.2 and it worked fine.

**Comment by davisli** [comment]
Just tested with Operator 1.5.2 and it worked fine.

**Comment by vepatel** [comment]
@davisli this was fixed in 1.5.2 👍🏼
