### ISSUE TITLE
Fixed Error deploying the default config in openshift: failed to install release: values don't meet the specifications of the schema(s) in the following chart(s): nginx-ingress: - controller.ingressClass: Invalid type. Expected: object, given: string

### ISSUE THREAD

**Issue by Tokix** [nginxinc/nginx-ingress-helm-operator#200]
**Describe the bug**
When installing the openshift-operator "Nginx Ingress Operator" in default configuration Version nginx-ingress-operator.v2.0.2 and you select "Create NginxIngress" with the default configuration and click "create" you receive the following error: 

`failed to install release: values don't meet the specifications of the schema(s) in the following chart(s): nginx-ingress: - controller.ingressClass: Invalid type. Expected: object, given: string`

**To Reproduce**
1. Install Nginx Ingress Operator Version v2.0.2 from the frontend
2. Under Nginx Ingress Controller on the first page klick "Create Instance"
3. In the Yaml view of the opened page klick "Create"
4. Under the "Nginx Ingress Controller" Tab you see the status "Conditions: Initialized, ReleaseFailed"
5. Klicking on the Controller you see the Error under Messages: 

```
failed to install release: values don't meet the specifications of the schema(s) in the following chart(s):
nginx-ingress:
- controller.ingressClass: Invalid type. Expected: object, given: string
```

**Expected behavior**
It should be able to create the sample without issues to check if the setup is working

**Your environment**
* Version of the NGINX Ingress Operator - Nginx Ingress Operator
2.0.2 provided by NGINX Inc 
* Version of the Ingress Controller - Image Tag 3.3.2-ubi
* Version of Kubernetes: Openshift 4.13.10
* Kubernetes platform (e.g. Mini-kube or GCP)
* Using NGINX

**Additional context**
If the line 55 -> ingressClass: nginx is removed the installation proceeds

**Comment by ydixken** [comment]
I can confirm this bahaviour, this currently blocks us from upgrading to 3.3.2 without having to purge the operator.
