### ISSUE TITLE
How to upgrade the operator on Openshift?

### ISSUE THREAD

**Issue by llomgui** [nginxinc/nginx-ingress-helm-operator#232]
Hello,

The documentation is not very clear about the path to update the operator on Openshift.
According to this [markdown ](https://github.com/nginxinc/nginx-ingress-helm-operator/blob/main/docs/openshift-installation.md), we need to apply CRD as a prerequisite.

What is the next step?

On operator page, we can see the latest version available (2.1.0) but it's impossible to upgrade to it.

Current version: 1.5.0
Update channel: alpha
Update approval: Manual (Don't have any button to upgrade to the latest)

Thank you

**Comment by vepatel** [comment]
Hi @llomgui, can you please explain what you mean by ` impossible to upgrade to it.`, are their any logs which you can share as it'll help us understand the issue better. Thanks!

**Comment by llomgui** [comment]
Hello @vepatel,

There is no "seemless upgrade" step available on the operator, there is no button to update it.
Is there any way to do it manually? How to update to ClusterServiceVersion v1.5.2 for example?

Thank you

**Comment by llomgui** [comment]
@vepatel Thank you, it worked. I deleted the operator then re-installed it.

I had one error about IngressClass being a string instead of an object. Quick fixed adding name attribute.

Do I have to deal with CRD as indicated by the documentation?

**Comment by vepatel** [comment]
Hi @llomgui, or operator is helm based and unfortunately helm does not handle CRDs upgrades automatically so CRDs have to be applied manually as a pre-req.
see https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

**Comment by llomgui** [comment]
Thank you for you help. 👍
