### ISSUE TITLE
scc.yaml file is missing. Recieve a 404

### ISSUE THREAD

**Issue by mdditt2000** [nginxinc/nginx-ingress-helm-operator#46]
Enviroment: OpenShift 4.11

[root@ocp-installer crd-resource]# oc apply -f https://raw.githubusercontent.com/nginxinc/nginx-ingress-operator-helm/v1.2.0/resources/scc.yaml
error: unable to read URL "https://raw.githubusercontent.com/nginxinc/nginx-ingress-operator-helm/v1.2.0/resources/scc.yaml", server reported 404 Not Found, status code=404
[root@ocp-installer crd-resource]# oc apply -f https://raw.githubusercontent.com/nginxinc/nginx-ingress-operator-helm/v1.2.0/resources/scc.yaml

error: unable to read URL "https://raw.githubusercontent.com/nginxinc/nginx-ingress-operator-helm/v1.2.0/resources/scc.yaml", server reported 404 Not Found, status code=404

**Comment by lucacome** [comment]
Hi @mdditt2000 

looks like the link in the README is wrong, it should be https://raw.githubusercontent.com/nginxinc/nginx-ingress-helm-operator/v1.2.0/resources/scc.yaml, opening a PR to fix it now, thanks!
