### ISSUE TITLE
doc typo

### ISSUE THREAD

**Issue by mwardbopp** [nginxinc/nginx-ingress-helm-operator#56]
URL https://github.com/nginxinc/nginx-ingress-helm-operator/blob/main/docs/manual-installation.md

kubectl -f https://raw.githubusercontent.com/nginxinc/nginx-ingress-helm-operator/v1.2.1/resources/scc.yaml

should be:

kubectl apply -f https://raw.githubusercontent.com/nginxinc/nginx-ingress-helm-operator/v1.2.1/resources/scc.yaml

**Comment by lucacome** [comment]
Hi @mwardbopp 

thanks for catching this! I've opened a PR to fix it.
