### ISSUE TITLE
Nginx not finding/using globalconfiguration file & TransportServers aren't working

### ISSUE THREAD

**Issue by D1StrX** [nginxinc/nginx-ingress-helm-operator#99]
**Describe the bug**
A couple of things, chaining subjects

**Nginx controller**
- The NginxIngress CRD _deployment/pod_ doesn't have the `Command-line Arguments - -global-configuration=$(POD_NAMESPACE)/<nginx-configuration-name>`  

- When using the NginxIngress, it doesn' t create the globalconfiguration

` ` ` yaml
spec.controller.enableCustomResources: true
spec.controller.globalConfiguration: <nginx-controller-namespace>/<nginx-configuration-name>
` ` ` 

or

` ` `yaml
globalConfiguration:
  create: true
  spec:
    listeners:
    - name: example-tcp
      port: 8888
      protocol: TCP
` ` `

The controller.service.customports contains this config, and the port is visible on the service. (should this also be done on the controller?)
` ` ` 
customPorts:
    - name: example-tcp
      port: 8888
      protocol: TCP
      targetPort: example-app
` ` ` 

**TransportServers**
` ` ` 
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: example-tcp
  namespace: <nginx-controller-namespace>
spec:
  listener:
    name: example-tcp
    protocol: TCP
  upstreams:
    - name: example-app
      service: example-service
      port: 8888
  action:
    pass: example-app

` ` ` 

` ` ` 
apiVersion: k8s.nginx.org/v1alpha1
kind: GlobalConfiguration
metadata:
  name: example-tcp
  namespace: <nginx-controller-namespace>
spec:
  listeners:
    - name: example-tcp
      port: 8888
      protocol: TCP

` ` ` 

`k describe ts -n <nginx-controller-namespace> <ts>` 
Type     Reason    Age   From                      Message
Warning  Rejected  37s   nginx-ingress-controller  Listener example-tcp doesn't exist

The service and deployment are in a namespace, different from where the GC & TS is.

**To Reproduce**
1. Deploy nginx-operator using the documentation (git clone, version -> make -> deploy etc)
2. Create nginx controller using [NgninxIngress](https://github.com/nginxinc/nginx-ingress-helm-operator/blob/main/config/samples/charts_v1alpha1_nginxingress.yaml) 
3. Create GlobalConfiguration & TransportServer, as described above

**Expected behavior**
- GlobalConfiguration file is created when defining it in the NginxIngress
- NginxIngress is using the GlobalConfiguration 
- TransportServer is finding the listener

- Custom TCP/UDP ports can be used when having the Nginx Controller deployed through Nginx-Operator

**Your environment**
* Version of the NGINX Ingress Operator - v1.4.0
* Version of the Ingress Controller - 
* Version of Kubernetes. v1.26.3
* Kubernetes platform (e.g. Mini-kube or GCP). On-prem, ubuntu
* Using NGINX

**Additional context**
Goal is that a service, with a custom TCP/UDP port (eg 8888), via Ingress object can be used with the nginx.org controller (not the Kubernetes Nginx controller (which does work with custom tcp/udp)).

If someone could explain how to achieve this, would be great 😄 And the issue related to the globalconfiguration could be fixed/explained.

**Comment by haywoodsh** [comment]
Hi @D1StrX Thank you for reporting this issue. This might be due to an issue in the helm chart, as in https://github.com/nginxinc/kubernetes-ingress/issues/3753, where the command line argument should still be generated in the manifest, but the name of the `GlobalConfiguration` does not match the actual `GlobalConfiguration` created.

If this is the case, due to the way operator works, you can try the following to duplicate the existing `GlobalConfiguration` with the correct name
```
kubectl get gc nginxingress-sample-nginx-ingress -n nginx-ingress -o json \
        | jq '.metadata.name = "nginx-ingress"' \
        | kubectl apply -f -
```
Note that you will need to update the controller custom ports too.

Please let me know if this workaround fixes the error. We are evaluating ways to address this issue and will provide an official fix soon.

**Comment by D1StrX** [comment]
You are correct. GC named nginx-ingress and the argument in the pod matches and works now. Also the rejecting is gone on the TS, the first time.... After deploying a change to the nginx controller it breaks the TS and says 'AddedOrUpdatedWithError' 
```
Configuration for <namespace>/<TS> was added or updated ; but was not applied: error when updating config from ConfigMap: could not get newest config version: could not get expected version: 15 after 1m0s
```

So the service & controller need to have the custom ports?

Then I am still wondering what is needed on the ingress part, so it works with the created GC & TS. (I have it working with kubernetes nginx controller). Are there specific annotations to be used?

**Comment by D1StrX** [comment]
I managed to get it to work as well.. but the I had to use an example from the ngnix docs.. somewhere deep in Github of nginx repo. What still doesn't work is Aacustom name for the GC. Only _nginx-ingress-default-controller_ works (tested by letting the CRD create the config file).
